qqqqqqqqqqqqname: Debian base custom bleeding edge docker image for pika

on:
  workflow_dispatch:

env:
  IMAGE_NAME: pika-base-debian-container

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: user/app:latestqqqqqqqq
