name: Generate and commit apt configs

on:
  workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ghcr.io/pikaos-linux/pika-base-debian-container:latest
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:
    - uses: actions/checkout@v3

    - name: Generate apt pin and json files
      run: ./gen-apt-config.sh

    - name: Setup git and push
      run: git config --global user.name 'Github Workflow Action' && git config --global user.email 'hotrod.master@hotmail.com' && git config --global --add safe.directory /__w/pika-base-debian-container/pika-base-debian-container && git add . && git commit -am"Commited by GH Action - gen-apt-config.yml" && git push
